name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy to Azure VM
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: malik
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/malik/Service_Web/
            sudo git pull
            cd /home/malik/Service_Web/Micro_Services/BookService
            sudo dotnet publish -o /home/malik/IZZIBOOKS/BookService
            cd /home/malik/Service_Web/Micro_Services/UserService
            sudo dotnet publish -o /home/malik/IZZIBOOKS/UserService
            cd /home/malik/Service_Web/Micro_Services/GatewayService
            sudo dotnet publish -o /home/malik/IZZIBOOKS/GatewayService
            cd /home/malik/Service_Web/Micro_Services/Front
            sudo dotnet publish -o /home/malik/IZZIBOOKS/Front
            sudo systemctl restart bookservice.service
            sudo systemctl restart userservice.service
            sudo systemctl restart gatewayservice.service
            sudo systemctl restart front.service